apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: test
    custom:
      buildCommand: ./build.sh
      dependencies:
        dockerfile:
          path: pathto/Dockerfile
          buildArgs:
            file: foo
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/*
